Repository codemistic/Non-Code, pull requests merged in 2022-10, with the labels that each got.

#1 How does a blockchain work
  How-does-a-blockchain-work/How-does-a-blockchain-work.md
Labels: hacktoberfest, hacktoberfest-accepted

#2 Added file containing basics of docker
  Docker-basics/basics-of-docker.md
Labels: hacktoberfest, hacktoberfest-accepted

#5 Added an article on Margin vs padding
  Margin-vs-Padding/Blog.md
Labels: hacktoberfest, hacktoberfest-accepted

#4 Can-Bitcoin-Be-The-Future-Currency
  BITCOIN-Blog/BitcoinBLOG.md
  BITCOIN-Blog/image1.png
  BITCOIN-Blog/image2.png
  BITCOIN-Blog/image3.png
  BITCOIN-Blog/image4.png
Labels: hacktoberfest, hacktoberfest-accepted

#3 Added few DevOps Resources and Organized folder for further addition.
  DevOps Resources/Cloud Fundamentals/Cloud Fundamentals.pdf
  DevOps Resources/Cloud Fundamentals/Cloud-Basics.md
  DevOps Resources/Cloud Fundamentals/Types-of-VM-(EC2)(AWS).md
  DevOps Resources/Docker-basics/basics-of-docker.md
Labels: hacktoberfest, hacktoberfest-accepted

#6 Infosys Interview preparation Guide
  Infosys Interview Preparation Guide
Labels: hacktoberfest, hacktoberfest-accepted

#13 Added some resources and updated readme.md
  BITCOIN-Blog/BitcoinBLOG.md
  BITCOIN-Blog/image1.png
  BITCOIN-Blog/image2.png
  BITCOIN-Blog/image3.png
  BITCOIN-Blog/image4.png
  DevOps Resources/Cloud Fundamentals/Cloud-Basics.md
  DevOps Resources/Cloud Fundamentals/Types-of-VM-(EC2)(AWS).md
  DevOps Resources/Computer Networking/computer-networking.md
  DevOps Resources/Docker-basics/basics-of-docker.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#12 Added IP address intro pdf
  DevOps Resources/Ansible/Ansible .pdf
  DevOps Resources/IP-Address/IP_Address__.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#9 sql
  sql/MySQL Notes For Pros.pdf
  sql/SQL Notes For Pros.pdf
  sql/sql_tutorial.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#8 What is blockchain?
  What is blockchain?
Labels: hacktoberfest, hacktoberfest-accepted

#11 a [200~dded resources links for devops and cheatsheets for sql, http …
  CheatSheets/Tech Interview Preparation Websites.pdf
  CheatSheets/http-status-codes.pdf
  CheatSheets/sql-cheat-sheet.pdf
  DevOps-Resources-Links/Devops-Resources.xlsx
Labels: hacktoberfest, hacktoberfest-accepted

#10 About Blockchain Hashing
  Blockchain Hashing
Labels: hacktoberfest, hacktoberfest-accepted

#7 HTML 101
  HTML 101/HTML 101.html
  HTML 101/HTML 101.md
Labels: hacktoberfest, hacktoberfest-accepted

#24 Updated README.md
  README.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#37 Update What is blockchain?
  What is blockchain?
Labels: hacktoberfest, hacktoberfest-accepted

#15 CSS 101
  CSS 101/CSS 101 Markdown/CSS 101 374a1b23f1d14e78941b81d9cadfe730.md
  CSS 101/CSS 101 Markdown/CSS 101 374a1b23f1d14e78941b81d9cadfe730/20220727_164004.jpg
  CSS 101/CSS 101 Markdown/CSS 101 374a1b23f1d14e78941b81d9cadfe730/20220727_172325.jpg
  CSS 101/CSS 101 Markdown/CSS 101 374a1b23f1d14e78941b81d9cadfe730/qsd75ur1lyq5s4dm0zar.jfif
  CSS 101/CSS HTML/CSS 101 374a1b23f1d14e78941b81d9cadfe730.html
  CSS 101/CSS HTML/CSS 101 374a1b23f1d14e78941b81d9cadfe730/20220727_164004.jpg
  CSS 101/CSS HTML/CSS 101 374a1b23f1d14e78941b81d9cadfe730/20220727_172325.jpg
  CSS 101/CSS HTML/CSS 101 374a1b23f1d14e78941b81d9cadfe730/qsd75ur1lyq5s4dm0zar.jfif
Labels: hacktoberfest, hacktoberfest-accepted

#50 Create Cpp.md
  CheatSheets/Cpp.md
Labels: hacktoberfest, hacktoberfest-accepted

#31 I have added the credit to all the open-source contributions
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#34 added kubernetes architechture file in devops resources
  DevOps Resources/Kubernetes/kubernetes-architecture.md
Labels: hacktoberfest, hacktoberfest-accepted

#49 Hacktoberfest-2022
  CSS Cheatsheet.pdf
  Django.pdf
  HTML Cheatsheet.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#46 Create Interview Preparation
  Interview Preparation - SQL, Python, Stats
Labels: hacktoberfest, hacktoberfest-accepted

#45 Added Verilog cheetsheet
  CheatSheets/verilog.md
Labels: hacktoberfest, hacktoberfest-accepted

#44 Update HTML 101.md
  HTML 101/HTML 101.md
Labels: hacktoberfest, hacktoberfest-accepted

#43 Cheatsheet for solidity
  CheatSheet-for-SOLIDITY.md
Labels: hacktoberfest, hacktoberfest-accepted

#42 AWT Notes Added
  AWT Notes/AWT_notes/ADO.Net DataRow Column Reader.pdf
  AWT Notes/AWT_notes/ADO.Net Datatable.pdf
  AWT Notes/AWT_notes/ADO.net.pdf
  AWT Notes/AWT_notes/ASP.NET State Management.pdf
  AWT Notes/AWT_notes/ASP.Net.pdf
  AWT Notes/AWT_notes/AWT 1st unit.pdf
  AWT Notes/AWT_notes/AWT Unit 2.pdf
  AWT Notes/AWT_notes/AWT Unit 3-1.pdf
  AWT Notes/AWT_notes/AWT Unit 4.pdf
  AWT Notes/AWT_notes/JSON.pdf
  AWT Notes/AWT_notes/WSDL_Web Service Description Language.pdf
  AWT Notes/AWT_notes/Web service.pdf
  AWT Notes/AWT_notes/asp.net rich controls.PDF
  AWT Notes/AWT_notes/asp.net_basic_controls.pdf
  AWT Notes/AWT_notes/asp.net_configuration.pdf
  AWT Notes/AWT_notes/asp.net_custom_controls.pdf
  AWT Notes/AWT_notes/asp.net_validators.pdf
  AWT Notes/AWT_notes/intro to sql server.pdf
  BITCOIN-Blog/BitcoinBLOG.md
  DevOps Resources/Computer Networking/computer-networking.md
  How-does-a-blockchain-work/How-does-a-blockchain-work.md
  What is blockchain?
Labels: hacktoberfest, hacktoberfest-accepted

#40 Add the cheat sheet of Bootstrap
  CheatSheets/Bootstrap-Cheat-Sheet.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#35 Added git cheat sheet
  CheatSheets/git-cheat-sheet.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#19 added linux blog
  Linux-Blog/Linux_Basics.md
Labels: hacktoberfest, hacktoberfest-accepted

#20 feat: add blog and analysis on data story telling
  Data story telling/Analysis.png
  Data story telling/Data story telling.txt
Labels: hacktoberfest, hacktoberfest-accepted

#21 SKYPE-How Microsoft Ruined It!
  Skype-BLOG/SKYPE.md
  Skype-BLOG/image1.png
  Skype-BLOG/image2.png
  Skype-BLOG/image3.png
  Skype-BLOG/image4.png
  Skype-BLOG/image5.png
  Skype-BLOG/image6.png
  Skype-BLOG/image7.png
Labels: hacktoberfest, hacktoberfest-accepted

#22 Is Netflix on the same edge as of 2007 Add files via upload
  Is Netflix on the same edge as of 2007/Is-Netflix-on-the-same-edge-as-of-2007.md
Labels: hacktoberfest, hacktoberfest-accepted

#27 Add files via upload
  CheatSheets/CheatSheetTimeComplexitySortings.jpeg
Labels: hacktoberfest, hacktoberfest-accepted

#30 Add files via upload
  Inkspace Textures/Texture1.png
  Inkspace Textures/Texture10.png
  Inkspace Textures/Texture11.png
  Inkspace Textures/Texture12.png
  Inkspace Textures/Texture13.png
  Inkspace Textures/Texture14.png
  Inkspace Textures/Texture15.png
  Inkspace Textures/Texture2.png
  Inkspace Textures/Texture3.png
  Inkspace Textures/Texture4.png
  Inkspace Textures/Texture5.png
  Inkspace Textures/Texture6.png
  Inkspace Textures/Texture7.png
  Inkspace Textures/Texture8.png
  Inkspace Textures/Texture9.png
Labels: hacktoberfest, hacktoberfest-accepted

#52 Add Python_CheatSheet_For_Beginners.Pdf in Cheatsheets Folder
  CheatSheets/Python_CheatSheet_For_Beginners.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#53 Create Python.md
  CheatSheets/Python.md
Labels: hacktoberfest, hacktoberfest-accepted

#54 Update needed a little type error.
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#59 Interview Preparation Notes added
  Interview Preparation Notes/personal non tech que.pdf
  Interview Preparation Notes/tech question.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#58 Create Data_structure_and_Algorithm.md
  CheatSheets/Data_structure_and_Algorithm.md
Labels: hacktoberfest, hacktoberfest-accepted

#57 Create Data Structure and Algorithm Cheatsheets.md
  Data Structure and  Algorithm Cheatsheets.md
Labels: hacktoberfest, hacktoberfest-accepted

#56 added linux-cheatsheet
  CheatSheets/Css-cheat-sheet.pdf
  CheatSheets/HTML-Cheat-Sheet.pdf
  CheatSheets/javascript-cheat-sheet.pdf
  CheatSheets/linux-command-line.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#77 Added how Google Maps track traffic?
  Google maps/Crowdsourcing.md
  Google maps/How-AI-helps-predict-traffic-and-determine-routes.md
  Google maps/How-Do-Google-Maps-Know-About-Traffic-Conditions.md
  Google maps/How-do-Google-Maps-know-about-current-traffic-conditions.md
Labels: hacktoberfest, hacktoberfest-accepted

#75 Add how https work
  DevOps Resources/Computer Networking/how-does-https-work.md
Labels: hacktoberfest, hacktoberfest-accepted

#74 Add binary trees sheet
  CheatSheets/binary_trees.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#73 Created UIUX Beginners Guide.md
  Creative Resume Template/Resume.md
  UIUX/UIUX Beginners Guide.md
Labels: hacktoberfest, hacktoberfest-accepted

#72 about_priority_queue
  All_about_priority_queues_in_c++/Priority_queues.md
Labels: hacktoberfest, hacktoberfest-accepted

#71 minikube file is added in kubernetes folder
  DevOps Resources/Kubernetes/minikube-tutorial.md
Labels: hacktoberfest, hacktoberfest-accepted

#67 Twitter Banner
  twitter banner.png
Labels: hacktoberfest, hacktoberfest-accepted

#66 Create DNS.md
  Basics of Internet/DNS.md
Labels: hacktoberfest, hacktoberfest-accepted

#65 The linux cheatsheet
  CheatSheets/Linux-Cheat-Sheet-Sponsored-By-Loggly-2.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#64 Create Graph Cheat Sheet
  CheatSheets/Graph Cheat Sheet
Labels: hacktoberfest, hacktoberfest-accepted

#79 Create MongoDB_Cheatsheet.md
  CheatSheets/MongoDB_Cheatsheet.md
Labels: hacktoberfest, hacktoberfest-accepted

#93 CSS em vs rem
  WhatsApp Image 2022-10-06 at 6.21.20 PM.jpeg
Labels: hacktoberfest, hacktoberfest-accepted

#102 Updated as per Maintainer's comment.
  Frontend Resources/CSS/Types of CSS.pdf
  Types of CSS/Types of CSS.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#104 Easy way to avoid UnicodeDecodeError
  python unicode error/avoid UnicodeDecodeError in python.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#96 Created Markdown File of CP Guide
  Competitive Programming guide/Guided Cp.md
Labels: hacktoberfest, hacktoberfest-accepted

#106 Update Cpp.md
  CheatSheets/Cpp.md
Labels: hacktoberfest, hacktoberfest-accepted

#105 Git Resources
  Git Resources/Git commands.pdf
  Git VS GitHub/Git VS GitHub.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#103 Adding REST_API documentation
  Web Development/REST_API.md
Labels: hacktoberfest, hacktoberfest-accepted

#107 Added Shortcut Keys Cheatsheet ( Issue #14)
  CheatSheets/shortcut-keys-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-accepted

#100 Added summary of node.js
  Web Development/Backend/Nodejs.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#116 Azure Interview Questions
  Interview Preparation Notes/Azure Interview Questions
Labels: hacktoberfest, hacktoberfest-accepted

#112 Added A blog on BASH Scripting
  A blog on BASH Scripting
Labels: hacktoberfest, hacktoberfest-accepted

#128 Cheat Sheet
  CheatSheets/Dart_Cheat_Sheet.md
Labels: hacktoberfest, hacktoberfest-accepted

#125 added ReactJs blog
  Web Development/Frontend/ReactJs.md
Labels: hacktoberfest, hacktoberfest-accepted

#119 AI and ML
  AI and ML/What is AI
  DBMS/SQL/SQL Join.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#115 Create NoSQLDatabases.md
  NoSQLDatabases.md
Labels: hacktoberfest, hacktoberfest-accepted

#84 Create most used commands.md
  LINUX/most used commands.md
Labels: hacktoberfest, hacktoberfest-accepted

#129 Added a blog
  blog/markdown_html.md
Labels: hacktoberfest, hacktoberfest-accepted

#124 Added Documentation files on DBMS and Devops.
  DBMS/SQL/About DBMS/Introduction.md
  DBMS/SQL/About DBMS/More-on-Database-1.md
  DBMS/SQL/About DBMS/More-on-Database-2.md
  DevOps Resources/Docker-basics/essential-docker-commands.md
Labels: hacktoberfest, hacktoberfest-accepted

#132 New Cheatsheet added: Google Search Shortcuts
  CheatSheets/Google_Search_Shortcuts.md
Labels: hacktoberfest, hacktoberfest-accepted

#133 ReactJs CheatSheet 2022
  CheatSheets/React_Js_CheatSheet.md
  Competitive Programming guide/Curated_Guide_CP.md
Labels: hacktoberfest, hacktoberfest-accepted

#134 ADDED JAVA OOPS NOTES
  Java/Abstract.pdf
  Java/Access_Modifier.pdf
  Java/Class_java.pdf
  Java/Constructor_this_finalize.pdf
  Java/Enums.pdf
  Java/Inheritance.pdf
  Java/Interfaces.pdf
  Java/Overloading.pdf
  Java/Overriding.pdf
  Java/Packages.pdf
  Java/Static_java.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#135 I have added Linux Cheatsheet
  LINUX/Linux Cheatsheet
Labels: hacktoberfest, hacktoberfest-accepted

#139 Updated Guide.md and added some usefull stuff
  CP and Related/Guide.txt
Labels: hacktoberfest, hacktoberfest-accepted

#167 Add files via upload
  Frontend-Resources-main/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#166 HOW TO CREATE FIRST REACT NATIVE APP
  REACT NATIVE/HOW TO CREATE FIRST REACT NATIVE APP.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#165 Kindly check my article. Thanks.
  Automated Deployment Webapp/JENKINS+GRADLE+DOCKER+AWS.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#164 Added one folder of Networking.
  Networking/Different Networking Protocols
  Networking/Introduction to Networking and Data Flow
  Networking/OSI Model
Labels: hacktoberfest, hacktoberfest-accepted

#162 Create BlockChain_Guide.md
  BlockChain and Crypto/BlockChain_Guide.md
Labels: hacktoberfest, hacktoberfest-accepted

#161 Functions in c plus plus
  7.1 Functions.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#160 graph_data_structure.md
  CheatSheets/graph_data_structure.md
Labels: hacktoberfest, hacktoberfest-accepted

#159 Add pdf about callback functions
  NodeJs/Pdf/Callback_function_basics.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#158 Flutter folder
  Flutter/Flutter .pdf
Labels: hacktoberfest, hacktoberfest-accepted

#156 What is favicon in SEO ?
  what Is Favicon in SEO (2).docx
Labels: hacktoberfest, hacktoberfest-accepted

#154 Added Git CheatSheet
  CheatSheets/WhatsApp Image 2022-10-07 at 7.04.21 PM.jpeg
Labels: hacktoberfest, hacktoberfest-accepted

#153 Markdown cheatsheet
  CheatSheets/Markdown_CheatSheet.md
  CheatSheets/PythonCheatsheet.md
  CheatSheets/linux-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-accepted

#147 added new coding sites to readme file
  Competitive Programming/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#146 Updated arrow symbol, for professional look
  C++_Sort()_inner_implementation details/c++_sort_inner_implementation_details.md
Labels: hacktoberfest, hacktoberfest-accepted

#144 Added Data Science CheatSheet
  CheatSheets/Data Science Cheatsheet .pdf
Labels: hacktoberfest, hacktoberfest-accepted

#143 Added C# Conditions & Loops document
  C#/csharp-conditions-loops-cheatsheet.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#151 Css grid fr unit
  IMG_20221008_154843.jpg
Labels: hacktoberfest, hacktoberfest-accepted

#150 Create UI Design Trends.md
  UI Design Trends.md
Labels: hacktoberfest, hacktoberfest-accepted

#173 OSI_TCP_IP Model
  Networking/OSI_TCP_IP.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#172 Create Sql CheatSheet
  CheatSheets/Sql_CheatSheet.md
Labels: hacktoberfest, hacktoberfest-accepted

#171 create git_cheatsheet
  CheatSheets/git_cheatsheet.md
Labels: hacktoberfest, hacktoberfest-accepted

#113 Create How to Design Systems.pdf
  Design Systems/How to Design Systems.pdf
  Jmeter/Install Apache JMeter-HathaipachI.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#188 Added 5 ways to center div
  IMG_20221009_190031.jpg
Labels: hacktoberfest, hacktoberfest-accepted

#168 RoadMap to SDE
  Interview Preparation Notes/RoadMap to SDE
Labels: hacktoberfest, hacktoberfest-accepted

#169 Updated Frontend resources
  Frontend-Resources-main/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#170 Basics of BinarySearch
  Basics of BinarySearch/BinarySearch_notes.pdf
  Basics of BinarySearch/binarySearch.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#177 Added methods to sort in descending order using backward iterator
  C++_Sort()_inner_implementation details/c++_sort_inner_implementation_details.md
Labels: hacktoberfest, hacktoberfest-accepted

#178 Updated header info and added code of min heap priority queue
  CheatSheets/Cpp.md
Labels: hacktoberfest, hacktoberfest-accepted

#181 Create Amazon Interview question
  Interview Preparation Notes/Amazon Interview question
Labels: hacktoberfest, hacktoberfest-accepted

#183 Adding Kubernetes/kubectl cheatsheet
  CheatSheets/Kubernetes_cheatsheet.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#185 CYBER SECURITY AND ETHICAL HACKING FROM SCRATCH
  CYBERSECURITY/CYBER SECURITY FROM SCRATCH.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#189 new type of css added
  Types of CSS/tailwind.md
Labels: hacktoberfest, hacktoberfest-accepted

#196 Added Go-cheatsheet.md
  CheatSheets/Go-cheatsheet.md
Labels: hacktoberfest, hacktoberfest-accepted

#200 Added LR models with steps to implement
  AI and ML/Linear Regression Model/Linearregression.ipynb
  AI and ML/Linear Regression Model/Readme.md
  AI and ML/Linear Regression Model/Screenshot 2022-10-07 153212.png
  AI and ML/Linear Regression Model/Screenshot 2022-10-07 153430.png
  AI and ML/Linear Regression Model/Week2_LR.ipynb
  AI and ML/Linear Regression Model/Week2_Regression.ipynb
  AI and ML/Linear Regression Model/areas.csv
  AI and ML/Linear Regression Model/homeprices.csv
  AI and ML/Linear Regression Model/iris.csv
  AI and ML/Linear Regression Model/prediction.csv
  AI and ML/Linear Regression Model/test_data.xlsx
Labels: hacktoberfest, hacktoberfest-accepted

#229 Aditibagaddeo22 communication s
  Communication_skills/communication.md
Labels: hacktoberfest, hacktoberfest-accepted

#203 Frontend developer RoadMap
  Frontend-Resources-main/Frontend Developer RoadMap
Labels: hacktoberfest, hacktoberfest-accepted

#206 Accenture sample questions for tech interviews
  Interview Preparation Notes/ACCENTURE SAMPLE QUESTIONS.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#228 Kindly Accept my merge request
  AWS/Deploy_Webserver_n_Database_AWS.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#224 INTRODUCTION_TO_FIRE_BASE
  FIRE_BASE/INTRODUCTION_TO_FIRE_BASE.pdf
  NATIVE_SCRIPT/NATIVE_SCRIPT_INTRODUCTION.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#212 Communication Skills Roadmap
  Communication Skills/Roadmap
Labels: hacktoberfest, hacktoberfest-accepted

#214 Added notes for issue192
  Interview Preparation Notes/Barclays_Preparation.md
Labels: hacktoberfest, hacktoberfest-accepted

#218 Create Flex-Notes
  Web Development/Frontend/Flex-Notes
Labels: hacktoberfest, hacktoberfest-accepted

#254 Added frequently asked HR Q&A
  behavioural questions HR.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#253 Create Machine Learning in detail
  AI and ML/Machine Learning in detail
Labels: hacktoberfest, hacktoberfest-accepted

#251 Using NGINX as a reverse-proxy
  DevOps Resources/Nginx/reverse-proxy-using-subdomains.md
Labels: hacktoberfest, hacktoberfest-accepted

#249 Add files via upload
  Air-doodle/Air-canvas.py
Labels: hacktoberfest, hacktoberfest-accepted

#248 Added Git Commands pdf
  Git Resources/GitHub.Git.Cheatsheet.pdf
  Java/OOPs_RealLife_Examples
Labels: hacktoberfest, hacktoberfest-accepted

#256 Create What is Deep Learning
  AI and ML/What is Deep Learning
Labels: hacktoberfest, hacktoberfest-accepted

#277 Add files via upload
  ikigai _the purpose of being .pdf
Labels: hacktoberfest, hacktoberfest-accepted

#238 Added an article on AI_Grand_Challenges_and_Emerging_Economies
  AI and ML/A Comprehensive Guide on How To Get Started with Machine Learning _ by Prakriti Shetty _ Sep, 2022 _ Medium.pdf
  AI and ML/AI-grand-challenges-and-emerging-economies.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#246 Linked List cheatsheet
  CheatSheets/Linked List Notes.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#261 some of the top python libraries
  some top python libraries.docx
Labels: hacktoberfest, hacktoberfest-accepted

#289 Added documentation for issue 191
  Interview Preparation Notes/JP_Morgan_CFG.md
Labels: hacktoberfest, hacktoberfest-accepted

#220 Created JavaScript -Functions and Arrays
  Java/Language tools for Java
  Web Development/JavaScript -Functions and Arrays
Labels: hacktoberfest, hacktoberfest-accepted

#231 Interview Preparation Q/A in organised way and the best CV Building Templates and Sample
  Interview Preparation Notes/coding-interview_Leetcode with solutions.pdf
  Miscellaneous/CV Building/CV Format.docx
  Miscellaneous/CV Building/Sample CV_Resumes-cover.pdf
  coding-interview_Leetcode with solutions.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#225 Added DataLink_layer in OSI model
  Networking/DataLink_layer.md
Labels: hacktoberfest, hacktoberfest-accepted

#257 Area Price Prediction Model
  AI and ML/Area Price Prediction Model
  AI and ML/Area_Price_Pred.ipynb
Labels: hacktoberfest, hacktoberfest-accepted

#267 Added Getting Started with React Guide
  Web Development/REACT NATIVE/Getting Started With React.js.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#266 React Native Core Components Article
  Mobile App Development/react-native-core-components.md
Labels: hacktoberfest, hacktoberfest-accepted

#265 Added Numpy Library Cheatsheet which is essential and important in ML
  AI and ML/Numpy Cheatsheet_MJ.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#268 ML
  ML/Clustering.ipynb
  ML/InterLevel DecisionTreeAlgo/Iris.csv
  ML/InterLevel DecisionTreeAlgo/IrisTree.png
  ML/InterLevel DecisionTreeAlgo/LGM Task (2).ipynb
  ML/K_mean.ipynb
  ML/README.md
  ML/begginer irisflower classification/iris.ipynb
  ML/begginer irisflower classification/task1.py
Labels: hacktoberfest, hacktoberfest-accepted

#271 Added Introduction to Mongodb Pdf
  Web Development/Backend/Introduction_To_Mongodb.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#235 NOSQL
  NOSQL
Labels: hacktoberfest, hacktoberfest-accepted

#269 why_redux_preferred_over_context-api
  All_about_constructors_in_c++/All_about_constructors_in_c++.md
  Why_redux_preferred_over_context_api/Redux_preferred_over_context.md
Labels: hacktoberfest, hacktoberfest-accepted

#263 Capgemini technical interview questions
  Interview Preparation Notes/Capgemini Interview Questions
Labels: hacktoberfest, hacktoberfest-accepted

#259 SQL Cheatsheet
  CheatSheets/SQL Cheatsheet
Labels: hacktoberfest, hacktoberfest-accepted

#244 Create UI-UX Design Learning Roadmap
  UI-UX Design Learning Roadmap/UI-UX Design Learning Roadmap
Labels: hacktoberfest, hacktoberfest-accepted

#234 Added some notes on BigData introduction
  Bigdata_Intro/BigData_1.txt
  Bigdata_Intro/BigData_2.txt
  Bigdata_Intro/BigData_3.txt
  Bigdata_Intro/BigData_4.txt
  Bigdata_Intro/BigData_5.txt
Labels: hacktoberfest, hacktoberfest-accepted

#233 computer networks history is added
  DevOps Resources/Computer Networking/HIstory of computer networks.md
Labels: hacktoberfest, hacktoberfest-accepted

#232 Ethereum Merge
  BlockChain and Crypto/Ethereum_Merge/Ethereum_Merge.md
Labels: hacktoberfest, hacktoberfest-accepted

#227 Created a Blog Angular vs React in Web development file
  Web Development/Frontend/Angular vs React.md
Labels: hacktoberfest, hacktoberfest-accepted

#336 ML pipeline explained
  AI and ML/ML pipeline.md
Labels: hacktoberfest, hacktoberfest-accepted

#335 Add MySQL Cheat Sheet
  Miscellaneous/CheatSheets/mysql-cheatSheet.md
Labels: hacktoberfest, hacktoberfest-accepted

#334 Create Git Cheat Sheet.md
  CheatSheets/Git Cheat Sheet.md
Labels: hacktoberfest, hacktoberfest-accepted

#333 added a cheatsheet of python
  CheatSheets/Python-Cheat-Sheet.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#332 Add files via upload
  CheatSheets/Javascript-Cheat-Sheet.pdf
Labels: hacktoberfest, hacktoberfest-accepted
